### ISSUE TITLE
Error 403 Invalid signature

### ISSUE THREAD

**Issue by SuNounix** [YunoHost-Apps/cachet_ynh#29]
hi,

I have a problem when registering a user, when I verify or manage my registration i have a 403 error Invalid signature.

![Firefox_Screenshot_2022-04-28T21-53-54 657Z](https://user-images.githubusercontent.com/91945628/165854318-59333e66-beec-457f-8f62-9dc2407d71b1.png)

And cachet's logs says :

`#0 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Routing\Middleware\ValidateSignature->handle(Object(Illuminate\Http\Request), Object(Closure))`

`#49 {main} {"identification":{"id":"50fc88bd-3a62-4259-9483-4545f2e871e1"},"exception":"[object] (Illuminate\\Routing\\Exceptions\\InvalidSignatureException(code: 0): Invalid signature. at /var/www/cachet/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ValidateSignature.php:25)`

Thanks for the help

**Comment by rodinux** [comment]
hi, I have the same problem, It seems impossible have available subscriptions...
