### ISSUE TITLE
Access is not created at installation

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/cachet_ynh#3]
On a fresh install (debian 9, Ynh 3.0.0.1), installation of Cachet on a dedicated subdomain, via the wabdmin interface, is successful. However, no access to the dashboard is created for the selected user. 

I managed to open an access following [this process](https://docs.cachethq.io/docs/frequently-asked-questions#section-how-do-i-reset-a-forgotten-password). The user was present but password was neither the Ynh'user password or the one provided at installation.

Do I miss something ? What log may be of use here ?

**Comment by JimboJoe** [comment]
Hi, I couldn't reproduce your issue: the controlled password is the one typed during installation.
Did you use any particular character by any chance...?

**Comment by Jaxom99** [comment]
No, it was only letters (upper and lower case). I'll try one more time and note all the details of the installation.

**Comment by JimboJoe** [comment]
I tried again on my production server: login OK, should I use my user login or e-mail...
what does this command return?
```
php -version
```

**Comment by dosch** [comment]
I only have acces to the webinterface at the moment... Under services Yunohost tells me I have PHP 7.0

**Comment by Jaxom99** [comment]
My version is `PHP 7.0.30-0+deb9u1`. I tried to auth with full email and just username, none was reckognized.

**Comment by JimboJoe** [comment]
I tried many tests, but still not reproduced... :tired_face:

Could you please try another installation and share the full logs?
```
yunohost app install cachet --debug
```

**Comment by dosch** [comment]
That just opened another pandora box....

```
$ yunohost app install cachet --debug
230  DEBUG loading actions map namespace 'yunohost'
256  DEBUG extra parameter classes loaded: ['ask', 'password', 'required', 'pattern']
257  DEBUG initializing base actions map parser for cli
258  DEBUG registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 213, in <module>
    timeout=opts.timeout,
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 133, in cli
    'parser_kwargs': parser_kwargs,
  File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 357, in init_interface
    return interface(amap, **kwargs)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 352, in __init__
    m18n.set_locale(get_locale())
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 139, in get_locale
    lang = locale.getdefaultlocale()[0]
  File "/usr/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by decentral1se** [comment]
On the latest Yunohost (3.6.4) and installing both 2.3.15 and 2.3.18 Cachet, I cannot see this issue. I was able to log into the dashboard without issue. Just wanted to leave this update.
