### ISSUE TITLE
nginx rewrite issue ?

### ISSUE THREAD

**Issue by XlllllllX** [YunoHost-Apps/cachet_ynh#5]
Hello,
On YNH up to date (fresh install, on week old).
When I try to access Cachet, I receive a 404.
The link in YNH sso is `https://my-dn.tld/c`

In /etc/nginx/conf.d/my-dn.d/cachet.conf at line 9 :
`  location /c {
    rewrite ^ /cindex.php$request_uri;
  }`
I corrected it with
`  location /c {
    rewrite ^ /c/index.php;
  }`
It works but the "dashboard" link is broken
`<a class="btn btn-link" href="/dashboard">Tableau de bord</a>`
It missing `/c` so I can't log in because the redirection to `auth/login` is broken to.

Best regards (thanks for your work)

**Comment by JimboJoe** [comment]
Hello,
As stated in the know issues in the README, this app must unfortunately necessarily be installed on the domain root... which isn't the case for you.

**Comment by XlllllllX** [comment]
Sorry, I never receive any notification about your answer.
All ok here, thank you very much.
