### ISSUE TITLE
Upgrade fails

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/cachet_ynh#7]
Upgrade fails on a debian VPS, with cachet installed on a dedicated subdomain, and Yunohost fuly upgraded (3.5.2.2). The "php-reload" step seems to time-out, and thus a part of the script is killed by the system.
See logs :https://paste.yunohost.org/raw/kayeguceyu

Thanks in advance for any input to this issue :)

**Comment by JimboJoe** [comment]
The composer process (in charge of updating PHP dependencies) got killed:
```
2019-06-02 18:23:41,387: WARNING - _common.sh: line 16: 15950 Killed                  COMPOSER_HOME="${workdir}/.composer" php "${workdir}/composer.phar" $@ -d "${workdir}" --quiet --no-interaction
```
I suspect you simply ran out of memory...

**Comment by Jaxom99** [comment]
meh, very possible on those small instances. So I guess I have to stop other services before getting to this update... 
Thanks for looking into it !
